development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: country_guessr_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: country_guessr_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: country_guessr_production
  # Si vous utilisez un service externe pour Redis, décommentez la ligne suivante et remplacez les informations par celles fournies par votre service
  # url: redis://:your_password@your_redis_host:6379/0
