default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: country_guessr_development
  username: admin
  password: admin
  host: localhost

test:
  <<: *default
  database: country_guessr_test
  username: admin
  password: admin
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
